apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whatsapp-01

namePrefix: instance-01-

resources:
  - ../../base
  - postgres.yaml

patches:
  - path: namespace-patch.yaml
  - path: secret-patch.yaml
  - path: ingress-patch.yaml

commonLabels:
  app.kubernetes.io/instance: instance-01

commonAnnotations:
  whatsapp.io/instance-id: "01"
