apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whatsapp-api
spec:
  rules:
    - host: whatsapp-04.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: instance-04-whatsapp-api
                port:
                  name: http
